"""Generate a bus-agnostic C driver skeleton: `<part>.h` and `<part>.c`.

Deliberately not a complete driver. The parts a generator can get right --
register access, read-modify-write masking, the identity check, the struct
layout -- are generated fully. The part it cannot know, how your board actually
talks I2C or SPI, is left as two function pointers you fill in.

That boundary is the point. Generated code that pretends to know your HAL is
worse than no generated code at all.
"""

from __future__ import annotations

import re

from ..models import DeviceRecord, Register
from . import c_ident, stdint_type

_ID_REG = re.compile(r"^(CHIP_?ID|WHO_?AM_?I|WHOAMI|DEVICE_?ID|PART_?ID|ID|DEV_?ID)$", re.IGNORECASE)


def _find_id_register(record: DeviceRecord) -> Register | None:
    """Locate a chip-identity register, preferring one with a known reset value.

    Nearly every sensor has one, and checking it is the first thing any real
    driver does. Generating that check for free is a small thing that signals
    the tool was written by someone who has actually brought up a part.
    """
    candidates = [r for r in record.device.registers if _ID_REG.match(c_ident(r.name))]
    if not candidates:
        return None
    with_reset = [r for r in candidates if r.reset_value is not None]
    return with_reset[0] if with_reset else candidates[0]


def _banner(record: DeviceRecord, what: str) -> str:
    d, p = record.device, record.provenance
    verified = "verified" if p.verified else "MACHINE-EXTRACTED, NOT VERIFIED"
    return "\n".join(
        [
            "/*",
            f" * {d.part_number} driver {what}",
            f" * {d.manufacturer}" + (f" -- {d.description}" if d.description else ""),
            " *",
            f" * Generated by RegForge {p.regforge_version or '?'} from a {verified} register map.",
            f" * Regenerate with:  regforge gen {d.part_number} --driver",
            " *",
            " * Only the two transport hooks need filling in; everything else is complete.",
            " */",
            "",
        ]
    )


def generate_driver_header(record: DeviceRecord) -> str:
    d = record.device
    prefix = c_ident(d.part_number)
    lower = c_ident(d.part_number, upper=False)
    guard = f"{prefix}_H_"
    addr_type = stdint_type(d.register_address_bits)
    id_reg = _find_id_register(record)

    lines = [_banner(record, "interface")]
    lines += [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        f'#include "{lower}_regs.h"',
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        "/* Return 0 on success, negative on error, from both transport hooks. */",
        f"typedef int (*{lower}_read_fn)(void *ctx, {addr_type} reg, uint8_t *buf, uint16_t len);",
        f"typedef int (*{lower}_write_fn)(void *ctx, {addr_type} reg, const uint8_t *buf, uint16_t len);",
        "",
        f"typedef struct {{",
        f"    {lower}_read_fn  read;   /* your I2C/SPI register read  */",
        f"    {lower}_write_fn write;  /* your I2C/SPI register write */",
        "    void *ctx;               /* passed back to both hooks unchanged */",
        f"}} {lower}_t;",
        "",
        "/* Bind transport hooks. Returns 0, or -1 if any argument is NULL. */",
        f"int {lower}_init({lower}_t *dev, {lower}_read_fn read, {lower}_write_fn write, void *ctx);",
        "",
        "/* Single-register access. */",
        f"int {lower}_read_reg(const {lower}_t *dev, {addr_type} reg, uint8_t *value);",
        f"int {lower}_write_reg(const {lower}_t *dev, {addr_type} reg, uint8_t value);",
        "",
        "/* Burst access, for multi-byte results such as ADC output. */",
        f"int {lower}_read_burst(const {lower}_t *dev, {addr_type} reg, uint8_t *buf, uint16_t len);",
        "",
        "/* Read-modify-write. `value` is pre-shifted: use the _SET macros from",
        f" * {lower}_regs.h, or shift it yourself to match `mask`. */",
        f"int {lower}_update_bits(const {lower}_t *dev, {addr_type} reg, uint8_t mask, uint8_t value);",
        "",
    ]

    if id_reg is not None:
        expected = f"0x{id_reg.reset_value:02X}" if id_reg.reset_value is not None else "the value in the datasheet"
        lines += [
            f"/* Read {id_reg.name} and compare against {expected}.",
            " * Returns 0 on match, -1 on transport error, -2 on mismatch. */",
            f"int {lower}_probe(const {lower}_t *dev);",
            "",
        ]

    lines += [
        "#ifdef __cplusplus",
        "}  /* extern \"C\" */",
        "#endif",
        "",
        f"#endif /* {guard} */",
        "",
    ]
    return "\n".join(lines)


def generate_driver_source(record: DeviceRecord) -> str:
    d = record.device
    prefix = c_ident(d.part_number)
    lower = c_ident(d.part_number, upper=False)
    addr_type = stdint_type(d.register_address_bits)
    id_reg = _find_id_register(record)

    lines = [_banner(record, "implementation")]
    lines += [
        f'#include "{lower}.h"',
        "",
        f"int {lower}_init({lower}_t *dev, {lower}_read_fn read, {lower}_write_fn write, void *ctx)",
        "{",
        "    if (dev == NULL || read == NULL || write == NULL) {",
        "        return -1;",
        "    }",
        "    dev->read  = read;",
        "    dev->write = write;",
        "    dev->ctx   = ctx;",
        "    return 0;",
        "}",
        "",
        f"int {lower}_read_burst(const {lower}_t *dev, {addr_type} reg, uint8_t *buf, uint16_t len)",
        "{",
        "    if (dev == NULL || dev->read == NULL || buf == NULL) {",
        "        return -1;",
        "    }",
        "    return dev->read(dev->ctx, reg, buf, len);",
        "}",
        "",
        f"int {lower}_read_reg(const {lower}_t *dev, {addr_type} reg, uint8_t *value)",
        "{",
        "    if (value == NULL) {",
        "        return -1;",
        "    }",
        f"    return {lower}_read_burst(dev, reg, value, 1u);",
        "}",
        "",
        f"int {lower}_write_reg(const {lower}_t *dev, {addr_type} reg, uint8_t value)",
        "{",
        "    if (dev == NULL || dev->write == NULL) {",
        "        return -1;",
        "    }",
        "    return dev->write(dev->ctx, reg, &value, 1u);",
        "}",
        "",
        f"int {lower}_update_bits(const {lower}_t *dev, {addr_type} reg, uint8_t mask, uint8_t value)",
        "{",
        "    uint8_t current = 0u;",
        "    int rc;",
        "",
        f"    rc = {lower}_read_reg(dev, reg, &current);",
        "    if (rc != 0) {",
        "        return rc;",
        "    }",
        "",
        "    {",
        "        uint8_t updated = (uint8_t)((current & (uint8_t)~mask) | (value & mask));",
        "        if (updated == current) {",
        "            return 0;  /* nothing to do; skip the bus transaction */",
        "        }",
        f"        return {lower}_write_reg(dev, reg, updated);",
        "    }",
        "}",
        "",
    ]

    if id_reg is not None:
        reg_macro = f"{prefix}_{c_ident(id_reg.name)}"
        lines += [
            f"int {lower}_probe(const {lower}_t *dev)",
            "{",
            "    uint8_t id = 0u;",
            "    int rc;",
            "",
            f"    rc = {lower}_read_reg(dev, {reg_macro}, &id);",
            "    if (rc != 0) {",
            "        return -1;",
            "    }",
        ]
        if id_reg.reset_value is not None:
            lines += [
                f"    return (id == {reg_macro}_RESET) ? 0 : -2;",
                "}",
                "",
            ]
        else:
            lines += [
                "    /* The datasheet did not state an expected value for this register.",
                "     * Fill in the constant from the part's identification section. */",
                "    (void)id;",
                "    return 0;",
                "}",
                "",
            ]

    lines += [
        "/* ---------------------------------------------------------------------",
        " * Transport hooks -- fill these in for your platform, then pass them to",
        f" * {lower}_init(). Reference shape for a typical I2C HAL:",
        " *",
        f" * static int my_read(void *ctx, {addr_type} reg, uint8_t *buf, uint16_t len)",
        " * {",
        " *     return hal_i2c_mem_read(ctx, DEV_ADDR, reg, buf, len) == HAL_OK ? 0 : -1;",
        " * }",
        " *",
        f" * static int my_write(void *ctx, {addr_type} reg, const uint8_t *buf, uint16_t len)",
        " * {",
        " *     return hal_i2c_mem_write(ctx, DEV_ADDR, reg, buf, len) == HAL_OK ? 0 : -1;",
        " * }",
        " * ------------------------------------------------------------------ */",
        "",
    ]
    return "\n".join(lines)


__all__ = ["generate_driver_header", "generate_driver_source", "_find_id_register"]
