"""Generate a bus-agnostic C driver skeleton: `<part>.h` and `<part>.c`.

Deliberately not a complete driver. The parts a generator can get right --
register access, read-modify-write masking, the identity check, the struct
layout -- are generated fully. The part it cannot know, how your board actually
talks I2C or SPI, is left as two function pointers you fill in.

That boundary is the point. Generated code that pretends to know your HAL is
worse than no generated code at all.

Register width is honoured rather than assumed. A part whose registers are all
16-bit gets a 16-bit accessor; emitting `uint8_t *value` for it would read half
a register and look plausible while doing so. Byte order on the wire is the one
thing the register map genuinely does not record, so it is a documented,
switchable assumption instead of a silent one.
"""

from __future__ import annotations

import re

from ..models import DeviceRecord, Register
from . import c_ident, stdint_type

_ID_REG = re.compile(r"^(CHIP_?ID|WHO_?AM_?I|WHOAMI|DEVICE_?ID|PART_?ID|ID|DEV_?ID)$", re.IGNORECASE)


def _find_id_register(record: DeviceRecord) -> Register | None:
    """Locate a chip-identity register, preferring one with a known reset value.

    Nearly every sensor has one, and checking it is the first thing any real
    driver does. Generating that check for free is a small thing that signals
    the tool was written by someone who has actually brought up a part.
    """
    candidates = [r for r in record.device.registers if _ID_REG.match(c_ident(r.name))]
    if not candidates:
        return None
    with_reset = [r for r in candidates if r.reset_value is not None]
    return with_reset[0] if with_reset else candidates[0]


def _uniform_width(record: DeviceRecord) -> int | None:
    """The register width shared by every register, or None if they differ.

    A device with mixed widths has no single correct typed accessor, so the
    generator refuses to invent one.
    """
    widths = {r.size_bits for r in record.device.registers if r.size_bits > 0}
    if len(widths) == 1:
        return widths.pop()
    return None


def _banner(record: DeviceRecord, what: str) -> str:
    d, p = record.device, record.provenance
    if p.verified:
        origin = f"verified register map (checked by {p.verified_by or 'unknown'})"
    elif p.extraction_model:
        origin = "MACHINE-EXTRACTED, NOT VERIFIED register map"
    else:
        origin = "hand-transcribed, NOT VERIFIED register map"

    return "\n".join(
        [
            "/*",
            f" * {d.part_number} driver {what}",
            f" * {d.manufacturer}" + (f" -- {d.description}" if d.description else ""),
            " *",
            f" * Generated by RegForge {p.regforge_version or '?'} from a {origin}.",
            f" * Regenerate with:  regforge gen {d.part_number} --driver",
            " *",
            " * Only the two transport hooks need filling in; everything else is complete.",
            " */",
            "",
        ]
    )


def generate_driver_header(record: DeviceRecord) -> str:
    d = record.device
    prefix = c_ident(d.part_number)
    lower = c_ident(d.part_number, upper=False)
    guard = f"{prefix}_H_"
    addr_type = stdint_type(d.register_address_bits)
    id_reg = _find_id_register(record)

    width = _uniform_width(record)
    reg_type = stdint_type(width) if width else "uint8_t"
    reg_bytes = (width // 8) if width else 1

    lines = [_banner(record, "interface")]
    lines += [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        f'#include "{lower}_regs.h"',
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]

    if width:
        lines += [
            f"/* Every register on this part is {width} bits wide. */",
            f"typedef {reg_type} {lower}_reg_t;",
            f"#define {prefix}_REG_BYTES {reg_bytes}u",
            "",
        ]
        if reg_bytes > 1:
            lines += [
                f"/* Byte order on the wire. The register map does not record it, so this is",
                f" * an assumption: most parts send the most-significant byte first, which is",
                f" * what this driver does by default. Check your datasheet -- if yours is",
                f" * little-endian, define {prefix}_LSB_FIRST before including this header. */",
                "",
            ]
    else:
        lines += [
            "/* This part mixes register widths, so there is no single correct typed",
            " * accessor. The byte-oriented API below is the honest surface: use",
            f" * {lower}_read_burst() with the width from the *_WIDTH macro in",
            f" * {lower}_regs.h for anything wider than one byte. */",
            f"typedef uint8_t {lower}_reg_t;",
            f"#define {prefix}_REG_BYTES 1u",
            "",
        ]

    lines += [
        "/* Return 0 on success, negative on error, from both transport hooks. */",
        f"typedef int (*{lower}_read_fn)(void *ctx, {addr_type} reg, uint8_t *buf, uint16_t len);",
        f"typedef int (*{lower}_write_fn)(void *ctx, {addr_type} reg, const uint8_t *buf, uint16_t len);",
        "",
        "typedef struct {",
        f"    {lower}_read_fn  read;   /* your I2C/SPI register read  */",
        f"    {lower}_write_fn write;  /* your I2C/SPI register write */",
        "    void *ctx;               /* passed back to both hooks unchanged */",
        f"}} {lower}_t;",
        "",
        "/* Bind transport hooks. Returns 0, or -1 if any argument is NULL. */",
        f"int {lower}_init({lower}_t *dev, {lower}_read_fn read, {lower}_write_fn write, void *ctx);",
        "",
        "/* Raw byte access. Use this for burst reads of measurement output. */",
        f"int {lower}_read_burst(const {lower}_t *dev, {addr_type} reg, uint8_t *buf, uint16_t len);",
        "",
        f"/* Whole-register access, {width or 8} bits at a time. */",
        f"int {lower}_read_reg(const {lower}_t *dev, {addr_type} reg, {lower}_reg_t *value);",
        f"int {lower}_write_reg(const {lower}_t *dev, {addr_type} reg, {lower}_reg_t value);",
        "",
        "/* Read-modify-write. `value` is pre-shifted: use the _SET macros from",
        f" * {lower}_regs.h, or shift it yourself to match `mask`. */",
        f"int {lower}_update_bits(const {lower}_t *dev, {addr_type} reg, "
        f"{lower}_reg_t mask, {lower}_reg_t value);",
        "",
    ]

    if id_reg is not None:
        expected = f"0x{id_reg.reset_value:02X}" if id_reg.reset_value is not None else "the value in the datasheet"
        lines += [
            f"/* Read {id_reg.name} and compare against {expected}.",
            " * Returns 0 on match, -1 on transport error, -2 on mismatch. */",
            f"int {lower}_probe(const {lower}_t *dev);",
            "",
        ]

    lines += [
        "#ifdef __cplusplus",
        '}  /* extern "C" */',
        "#endif",
        "",
        f"#endif /* {guard} */",
        "",
    ]
    return "\n".join(lines)


def generate_driver_source(record: DeviceRecord) -> str:
    d = record.device
    prefix = c_ident(d.part_number)
    lower = c_ident(d.part_number, upper=False)
    addr_type = stdint_type(d.register_address_bits)
    id_reg = _find_id_register(record)
    width = _uniform_width(record)
    reg_bytes = (width // 8) if width else 1

    lines = [_banner(record, "implementation")]
    lines += [
        f'#include "{lower}.h"',
        "",
        f"int {lower}_init({lower}_t *dev, {lower}_read_fn read, {lower}_write_fn write, void *ctx)",
        "{",
        "    if (dev == NULL || read == NULL || write == NULL) {",
        "        return -1;",
        "    }",
        "    dev->read  = read;",
        "    dev->write = write;",
        "    dev->ctx   = ctx;",
        "    return 0;",
        "}",
        "",
        f"int {lower}_read_burst(const {lower}_t *dev, {addr_type} reg, uint8_t *buf, uint16_t len)",
        "{",
        "    if (dev == NULL || dev->read == NULL || buf == NULL) {",
        "        return -1;",
        "    }",
        "    return dev->read(dev->ctx, reg, buf, len);",
        "}",
        "",
    ]

    # Byte assembly is written as a loop so one code path covers 1, 2 and 4
    # byte registers. At REG_BYTES == 1 it degenerates to a plain copy and the
    # compiler folds it away.
    shift_msb = f"(8u * ({prefix}_REG_BYTES - 1u - i))"
    shift_lsb = "(8u * i)"

    lines += [
        f"int {lower}_read_reg(const {lower}_t *dev, {addr_type} reg, {lower}_reg_t *value)",
        "{",
        f"    uint8_t buf[{prefix}_REG_BYTES];",
        f"    {lower}_reg_t acc = 0;",
        "    unsigned i;",
        "    int rc;",
        "",
        "    if (value == NULL) {",
        "        return -1;",
        "    }",
        "",
        f"    rc = {lower}_read_burst(dev, reg, buf, (uint16_t){prefix}_REG_BYTES);",
        "    if (rc != 0) {",
        "        return rc;",
        "    }",
        "",
        f"    for (i = 0u; i < {prefix}_REG_BYTES; i++) {{",
        f"#ifdef {prefix}_LSB_FIRST",
        f"        acc = ({lower}_reg_t)(acc | (({lower}_reg_t)buf[i] << {shift_lsb}));",
        "#else",
        f"        acc = ({lower}_reg_t)(acc | (({lower}_reg_t)buf[i] << {shift_msb}));",
        "#endif",
        "    }",
        "",
        "    *value = acc;",
        "    return 0;",
        "}",
        "",
        f"int {lower}_write_reg(const {lower}_t *dev, {addr_type} reg, {lower}_reg_t value)",
        "{",
        f"    uint8_t buf[{prefix}_REG_BYTES];",
        "    unsigned i;",
        "",
        "    if (dev == NULL || dev->write == NULL) {",
        "        return -1;",
        "    }",
        "",
        f"    for (i = 0u; i < {prefix}_REG_BYTES; i++) {{",
        f"#ifdef {prefix}_LSB_FIRST",
        f"        buf[i] = (uint8_t)(value >> {shift_lsb});",
        "#else",
        f"        buf[i] = (uint8_t)(value >> {shift_msb});",
        "#endif",
        "    }",
        "",
        f"    return dev->write(dev->ctx, reg, buf, (uint16_t){prefix}_REG_BYTES);",
        "}",
        "",
        f"int {lower}_update_bits(const {lower}_t *dev, {addr_type} reg, "
        f"{lower}_reg_t mask, {lower}_reg_t value)",
        "{",
        f"    {lower}_reg_t current = 0;",
        f"    {lower}_reg_t updated;",
        "    int rc;",
        "",
        f"    rc = {lower}_read_reg(dev, reg, &current);",
        "    if (rc != 0) {",
        "        return rc;",
        "    }",
        "",
        f"    updated = ({lower}_reg_t)((current & ({lower}_reg_t)~mask) | (value & mask));",
        "    if (updated == current) {",
        "        return 0;  /* nothing to do; skip the bus transaction */",
        "    }",
        "",
        f"    return {lower}_write_reg(dev, reg, updated);",
        "}",
        "",
    ]

    if id_reg is not None:
        reg_macro = f"{prefix}_{c_ident(id_reg.name)}"
        lines += [
            f"int {lower}_probe(const {lower}_t *dev)",
            "{",
            f"    {lower}_reg_t id = 0;",
            "    int rc;",
            "",
            f"    rc = {lower}_read_reg(dev, {reg_macro}, &id);",
            "    if (rc != 0) {",
            "        return -1;",
            "    }",
        ]
        if id_reg.reset_value is not None:
            lines += [
                f"    return (id == {reg_macro}_RESET) ? 0 : -2;",
                "}",
                "",
            ]
        else:
            lines += [
                "    /* The datasheet did not state an expected value for this register.",
                "     * Fill in the constant from the part's identification section. */",
                "    (void)id;",
                "    return 0;",
                "}",
                "",
            ]

    hook_note = (
        f" * Registers are {width} bits wide, so each access moves {reg_bytes} byte(s)."
        if width
        else " * Register widths vary on this part; `len` tells you how many bytes to move."
    )
    lines += [
        "/* ---------------------------------------------------------------------",
        " * Transport hooks -- fill these in for your platform, then pass them to",
        f" * {lower}_init().",
        hook_note,
        " *",
        " * Reference shape for a typical I2C HAL:",
        " *",
        f" * static int my_read(void *ctx, {addr_type} reg, uint8_t *buf, uint16_t len)",
        " * {",
        " *     return hal_i2c_mem_read(ctx, DEV_ADDR, reg, buf, len) == HAL_OK ? 0 : -1;",
        " * }",
        " *",
        f" * static int my_write(void *ctx, {addr_type} reg, const uint8_t *buf, uint16_t len)",
        " * {",
        " *     return hal_i2c_mem_write(ctx, DEV_ADDR, reg, buf, len) == HAL_OK ? 0 : -1;",
        " * }",
        " * ------------------------------------------------------------------ */",
        "",
    ]
    return "\n".join(lines)


__all__ = [
    "generate_driver_header",
    "generate_driver_source",
    "_find_id_register",
    "_uniform_width",
]
