"""Generate `<part>_regs.h`: addresses, masks, shifts and field accessors.

The header is the part of RegForge an engineer reads first, so it is written to
look hand-made: banner comment per register, bit ranges spelled the way the
datasheet spells them, accessor macros that do the read-modify-write shifting
correctly so nobody has to re-derive it at 2am.
"""

from __future__ import annotations

from ..models import BitField, DeviceRecord, Register
from . import NameAllocator, c_ident, hex_literal, stdint_type

_RULE = "/* " + "-" * 72 + " */"


def _banner(record: DeviceRecord, guard: str) -> list[str]:
    d, p = record.device, record.provenance
    pages = ""
    if p.source_pages:
        lo, hi = min(p.source_pages), max(p.source_pages)
        pages = f", pages {lo}-{hi}" if lo != hi else f", page {lo}"

    lines = [
        "/*",
        f" * {d.part_number} register map",
        f" * {d.manufacturer}" + (f" -- {d.description}" if d.description else ""),
        " *",
        f" * Generated by RegForge {p.regforge_version or '?'}. DO NOT EDIT BY HAND.",
        f" * Regenerate with:  regforge gen {d.part_number}",
        " *",
    ]
    if p.source_filename:
        lines.append(f" * Source:    {p.source_filename}{pages}")
    if p.source_sha256:
        lines.append(f" * SHA-256:   {p.source_sha256[:32]}...")
    if p.extraction_model:
        lines.append(f" * Extracted: {p.extraction_model} on {p.extracted_at or 'unknown date'}")
    # "NOT VERIFIED" is deliberately the same string the driver banner uses, so
    # a single grep across a source tree finds every unreviewed generated file.
    if p.verified:
        verified = f"yes, by {p.verified_by or 'unknown'}"
    else:
        how = "machine-extracted" if p.extraction_model else "hand-transcribed"
        verified = f"NOT VERIFIED -- {how}, review before trusting"
    lines.append(f" * Verified:  {verified}")
    lines += [
        " */",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]
    return lines


def _device_section(record: DeviceRecord, prefix: str) -> list[str]:
    d = record.device
    out = [_RULE, "/* Device */", _RULE, ""]

    if d.i2c_addresses:
        if len(d.i2c_addresses) == 1:
            out.append(f"#define {prefix}_I2C_ADDR{'':<18} {hex_literal(d.i2c_addresses[0], 8)}")
        else:
            for i, addr in enumerate(d.i2c_addresses):
                out.append(f"#define {prefix}_I2C_ADDR_{i:<16} {hex_literal(addr, 8)}")
    out.append(f"#define {prefix}_REG_ADDR_BITS{'':<12} {d.register_address_bits}u")
    out.append(f"#define {prefix}_REG_COUNT{'':<16} {len(d.registers)}u")
    if d.buses:
        out.append(f"/* Buses: {', '.join(b.value for b in d.buses)} */")
    out.append("")
    return out


def _field_lines(prefix: str, reg_name: str, f: BitField, reg_bits: int, alloc: NameAllocator) -> list[str]:
    fname = alloc.take(f"{prefix}_{reg_name}_{c_ident(f.name)}")
    rtype = stdint_type(reg_bits)
    mask = hex_literal(f.mask, reg_bits)

    span = f"[{f.bit_high}:{f.bit_offset}]" if f.bit_width > 1 else f"[{f.bit_offset}]"
    reset = f" reset {hex_literal(f.reset_value, f.bit_width)}" if f.reset_value is not None else ""
    desc = f" -- {f.description}" if f.description else ""
    out = [f"/*   {f.name} bits {span} {f.access.value}{reset}{desc} */"]

    pad = 46
    out.append(f"#define {fname + '_SHIFT':<{pad}} {f.bit_offset}u")
    out.append(f"#define {fname + '_WIDTH':<{pad}} {f.bit_width}u")
    out.append(f"#define {fname + '_MASK':<{pad}} {mask}")
    out.append(
        f"#define {fname + '_GET(reg)':<{pad}} "
        f"((({rtype})(reg) & {mask}) >> {f.bit_offset}u)"
    )
    out.append(
        f"#define {fname + '_SET(reg, val)':<{pad}} "
        f"((({rtype})(reg) & ({rtype})~{mask}) | ((({rtype})(val) << {f.bit_offset}u) & {mask}))"
    )

    for ev in f.enum_values:
        ename = alloc.take(f"{fname}_{c_ident(ev.name)}")
        comment = f"  /* {ev.description} */" if ev.description else ""
        out.append(f"#define {ename:<{pad}} {hex_literal(ev.value, max(4, f.bit_width))}{comment}")

    out.append("")
    return out


def _register_section(prefix: str, reg: Register, alloc: NameAllocator, addr_bits: int = 8) -> list[str]:
    rname = alloc.take(f"{prefix}_{c_ident(reg.name)}")
    pad = 46

    header = [
        _RULE,
        f"/* {reg.name} @ {hex_literal(reg.address, addr_bits)}"
        f"  {reg.access.value}  {reg.size_bits}-bit"
        + (f"  reset {hex_literal(reg.reset_value, reg.size_bits)}" if reg.reset_value is not None else "")
        + " */",
    ]
    if reg.description:
        header.append(f"/* {reg.description} */")
    header.append(_RULE)
    header.append("")

    body = [f"#define {rname:<{pad}} {hex_literal(reg.address, addr_bits)}"]
    body.append(f"#define {rname + '_WIDTH':<{pad}} {reg.size_bits}u")
    if reg.reset_value is not None:
        body.append(f"#define {rname + '_RESET':<{pad}} {hex_literal(reg.reset_value, reg.size_bits)}")
    body.append("")

    for f in reg.fields:
        if f.bit_width < 1 or f.bit_offset < 0 or f.bit_high >= reg.size_bits:
            body.append(f"/*   SKIPPED {f.name}: bit range is out of bounds for this register */")
            body.append("")
            continue
        body += _field_lines(prefix, c_ident(reg.name), f, reg.size_bits, alloc)

    return header + body


def generate_regs_header(record: DeviceRecord) -> str:
    """Return the complete text of `<part>_regs.h`."""
    prefix = c_ident(record.device.part_number)
    guard = f"{prefix}_REGS_H_"
    alloc = NameAllocator()

    lines: list[str] = []
    lines += _banner(record, guard)
    lines += _device_section(record, prefix)

    for reg in record.device.registers:
        lines += _register_section(prefix, reg, alloc, record.device.register_address_bits)

    lines += [
        "#ifdef __cplusplus",
        "}  /* extern \"C\" */",
        "#endif",
        "",
        f"#endif /* {guard} */",
        "",
    ]
    return "\n".join(lines)


__all__ = ["generate_regs_header"]
